### ISSUE TITLE
Fails silently on windows

### ISSUE THREAD

**Issue by josharian** [josharian/goversion#1]

**Comment by fgergo** [comment]
@josharian turns out it's easy to check for GOBUILDFAIL from command line. Change the following and silently failed make.bat will fail loudly:
line 166:
		script = "make.bat"
shall be:
		script = "make.bat --no-local & if x%GOBUILDFAIL%==x1 exit 1"

I don't know how you expect diffs, but for this simple change, I think this comment should suffice.

**Comment by fgergo** [comment]
@josharian 
tldr; like russ said: exec.LookPath("") shall be used on windows

For the record only:
I tried several hacks, none worked. Only 1 is remaining, if we executed a batch file, which would check for GOBUILDFAIL.
I could not get the value for GOBUILDFAIL in 1 line, only in at least 2 lines.
Also this won't work, only for 2 consecutive runs:
c:>make.bat --no-local && if x%GOBUILDFAIL%==x1 echo FAILFAIL
I also tried to use os.LookupEnv("GOBUILDFAIL") after cmd.Run(), but it does the lookup in a separate environment.

**Comment by fgergo** [comment]
@josharian pr ok? need anything else?

**Comment by josharian** [comment]
Thanks, @fgergo. I haven't had time to look at any of this, but will at some point soon.

I won't plan to look at your PR unless you've signed a Google CLA, though, since otherwise I can't contribute this code to the Go project. I tentatively plan to eliminate this repo and move the whole thing to golang.org/x/tools/cmd/goversion.

**Comment by fgergo** [comment]
@josharian I have signed the individual cla on 2010 November 22 7:30 , how would you like proof?

**Comment by josharian** [comment]
I'd just need to be able to look you up in the AUTHORS/CONTRIBUTORS file in the Go repo. Want to provide name/email for that purpose? If you don't want it public, feel free to email it to me directly -- my github username @ gmail. Thanks!

**Comment by fgergo** [comment]
I used fgergo@gmail.com to sign the cla.
I don't know the process how my email address finally gets into AUTHORS/CONTRIBUTORS.
I attached a screenshot in case this helps, though I doubt this helps. What next?
![cla](https://cloud.githubusercontent.com/assets/5156576/21071964/d3158a74-beb2-11e6-913e-c985bd319d96.png)

**Comment by josharian** [comment]
We ask @bradfitz for help. :)

**Comment by fgergo** [comment]
@josharian I doubt brad can be any help here, unless he looked at my invidual cla from "inside google" and manually inserted my email address into AUTHORS/CONTRIBUTORS.
If I was him, I'd decline.
If I understand correctly the contribution process won't handle the edge case we have here.
That means, any code from an external contributor can only be merged indirectly into the go tree, unless the contributor already had some code merged into the go tree previously.
That means even if I wanted to contribute anything non-trivial to goversion, I'd first have to contribute something directly to the go tree, until goversion is merged into the go tree.

**Comment by bradfitz** [comment]
@josharian, I confirm that fgergo@gmail.com has submitted the CLA.

**Comment by josharian** [comment]
Thanks, Brad.
